<?php

return [
    'ambition' => [
        'Dokter',
        'Insinyur',
        'Guru',
        'Dosen',
        'Kyai',
        'Ustadz/Ustadzah',
        'Pengacara',
        'Arsitek',
        'Pilot',
        'Ilmuwan',
        'Polisi',
        'Tentara',
        'Pemadam Kebakaran',
        'Perawat',
        'Akuntan',
        'Pengusaha',
        'Penyanyi',
        'Aktor',
        'Penulis',
        'Jurnalis',
        'Atlet',
        'Koki',
        'Desainer Grafis',
        'Animator',
        'Programmer',
        'Astronaut',
        'Psikolog',
        'Peneliti',
        'Petani',
        'Veterinarian',
        'Ahli Biologi',
        'Pengembang Game',
        'Penari',
        'Sutradara Film',
        'Fotografer',
        'Arkeolog',
        'Antropolog',
        'Ahli Geologi',
        'Ahli Kelautan',
        'Ahli Fisika',
        'Ahli Kimia',
        'Ahli Matematika',
        'Ahli Ekonomi',
        'Pustakawan',
        'Diplomat',
        'Pekerja Sosial',
        'Pelukis',
        'Pemain Musik',
        'Desainer Interior',
        'Penata Busana',
        'Manajer Proyek',
        'Konsultan Keuangan',
        'Broker Saham',
        'Pilot Drone',
        'Ahli IT',
        'Pengembang Web',
        'Ahli SEO',
        'Spesialis Pemasaran Digital',
        'Ahli Data',
        'Pengrajin',
        'Tukang Kayu',
        'Montir',
        'Teknisi Listrik',
        'Ahli Mekanik',
        'Ahli Robotik',
        'Ahli AI',
        'Ahli Keamanan Siber',
        'Editor Video',
        'Produser Musik',
        'Pengacara Hak Asasi Manusia',
        'Advokat Lingkungan',
        'Aktivis Sosial',
        'Ahli Sumber Daya Manusia',
        'Manajer Hotel',
        'Chef Pastry',
        'Barista',
        'Pemandu Wisata',
        'Penata Rambut',
        'Penata Rias',
        'Penyiar Radio',
        'Penyiar TV',
        'Influencer Media Sosial',
        'Blogger',
        'Vlogger',
        'Streamer Game',
        'Desainer Produk',
        'Ahli Logistik',
        'Penilai Properti',
        'Arsitek Lanskap',
        'Ahli Nutrisi',
        'Terapis Fisik',
        'Ahli Kesehatan Masyarakat',
        'Ahli Gizi',
        'Pakar Pertanian',
        'Insinyur Pangan',
        'Konsultan Pendidikan',
        'Pengembang Aplikasi Mobile',
        'Pengembang Perangkat Lunak',
        'Ahli Forensik',
        'Ahli Bioteknologi',
        'Pengusaha Startup',
        'Manajer Pemasaran',
        'Manajer Penjualan',
        'Manajer Sumber Daya Alam',
        'Manajer Produksi',
        'Manajer Operasional',
        'Manajer Risiko',
        'Manajer Rantai Pasok',
        'Manajer Hubungan Masyarakat',
        'Manajer Komunikasi',
        'Spesialis Keberlanjutan',
        'Ahli Lingkungan',
        'Ahli Hukum Internasional',
        'Ahli Perpajakan',
        'Ahli Keuangan Syariah',
        'Ahli Ekonomi Syariah',
        'Peneliti Pasar',
        'Analis Data',
        'Analis Bisnis',
        'Analis Keuangan',
        'Analis Kredit',
        'Analis Risiko',
        'Penasihat Investasi',
        'Penilai Kredit',
        'Pengacara Perusahaan',
        'Pengacara Pidana',
        'Pengacara Keluarga',
        'Pengacara Imigrasi',
        'Pengacara Pajak',
        'Pengacara Properti',
        'Pengacara Kekayaan Intelektual',
        'Pengacara Hak Cipta',
        'Pengacara Paten',
        'Pengacara Merek Dagang',
        'Pengacara Kontrak',
        'Pengacara Warisan',
        'Pengacara Pengadilan',
        'Pengacara Arbitrase',
        'Pengacara Mediasi',
        'Pengacara Litigasi',
        'Pengacara Hukum Perdata',
        'Pengacara Hukum Tata Negara',
        'Pengacara Hukum Internasional',
        'Pengacara Hukum Bisnis',
        'Pengacara Hukum Lingkungan',
        'Pengacara Hukum Pidana',
        'Pengacara Hukum Keluarga',
        'Pengacara Hukum Imigrasi',
        'Pengacara Hukum Pajak',
        'Pengacara Hukum Properti',
        'Pengacara Hukum Kekayaan Intelektual',
        'Pengacara Hukum Hak Cipta',
        'Pengacara Hukum Paten',
        'Pengacara Hukum Merek Dagang',
        'Pengacara Hukum Kontrak',
        'Pengacara Hukum Warisan',
        'Pengacara Hukum Pengadilan',
        'Pengacara Hukum Arbitrase',
        'Pengacara Hukum Mediasi',
        'Pengacara Hukum Litigasi',
        'Pengacara Hukum Perdata',
        'Pengacara Hukum Tata Negara',
        'Pengacara Hukum Internasional',
        'Pengacara Hukum Bisnis',
        'Pengacara Hukum Lingkungan',
        'Pengacara Hukum Pidana',
    ],

    'hobby' => [
        'Membaca',
        'Menulis',
        'Melukis',
        'Fotografi',
        'Berkebun',
        'Memasak',
        'Olahraga',
        'Mendaki',
        'Menjahit',
        'Musik',
        'Menonton film',
        'Bermain game',
        'Bermain musik',
        'Menari',
        'Memancing',
        'Traveling',
        'Memasak',
        'Menggambar',
        'Koleksi barang antik',
        'Merakit model kit',
        'Menyanyi'
    ],

    'housing_status' => [
        'Tidak ada',
        'Rumah sendiri',
        'Rumah orang',
        'Rumah milik keluarga',
        'Rumah milik kerabat',
        'Sewa/Rumah milik orang',
    ],

    'recidency_status' => [
        'Bermukim',
        'Tidak bermukim',
    ],
];