name: Laravel Release

on:
  push:
    branches:
      - main

jobs:
  deploy_development:
    name: Release web to development server
    if: startsWith(github.event.head_commit.message, 'release-development:')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to development with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.FTP_SERVER }}
          port: 21
          script_stop: true
          script: |
            cd public_html
            php artisan down
            git stash
            git checkout staging
            git pull origin staging
            composer install
            php artisan migrate --force
            php artisan optimize
            php artisan up
