on:
  push:
    branches:
      - staging

name: 🚀 Deploy website on push staging

jobs:
  deploy_development:
    name: 🎉 Deploy to development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to development with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SERVER_SSHKEY }}
          # passphrase: ${{ secrets.SSH_PASSPHRASE }}
          APP_PORT: 22
          script_stop: true
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/dev.bakid.id/public_html

            # Stop the application for maintenance
            php artisan down

            # Reset to the latest commit on 'staging' branch
            git fetch origin staging
            # git reset --hard origin/staging

            # Perform database migrations
            php artisan migrate --force

            # Install composer dependencies
            # composer install --no-interaction --no-dev --prefer-dist

            # Clear cache and optimize application
            php artisan optimize:clear

            php artisan config:cache

            # composer dump-autoload

            composer install --ignore-platform-reqs

            # Install npm dependencies and build assets
            npm install
            npm run build


            if [ ! -d "storage/app/public/kts" ]; then
                mkdir storage/app/public/kts
            fi
            if [ ! -d "storage/app/public/announcement" ]; then
                mkdir storage/app/public/announcement
            fi
            if [ ! -d "storage/app/public/proof" ]; then
                mkdir storage/app/public/proof
            fi
            if [ ! -d "storage/app/public/temp_images" ]; then
                mkdir storage/app/public/temp_images
            fi
            if [ ! -d "storage/app/public/student-photos" ]; then
                mkdir storage/app/public/student-photos
            fi
            if [ ! -d "storage/app/public/qrcode" ]; then
                mkdir storage/app/public/qrcode
            fi
            if [ ! -d "storage/app/public/parent-photos" ]; then
                mkdir storage/app/public/parent-photos
            fi
            if [ ! -d "storage/app/public/doc-kk" ]; then
                mkdir storage/app/public/doc-kk
            fi

            sudo chmod -R gu+w storage/
            sudo chmod -R guo+w storage/
            sudo chmod -R gu+w bootstrap/cache/
            sudo chmod -R guo+w bootstrap/cache/

            # php artisan log-viewer:publish
            # php artisan storage:link

            # Bring the application back online again
            php artisan up
